version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/cuping-fe # 리액트 프로젝트 디렉토리
    overwrite: yes
permissions:
  - object: /home/ubuntu/cuping-fe # 리액트 프로젝트 디렉토리
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
